### PR TITLE
limit $__interval_s to at least 1 second

### PR DESCRIPTION
**Pull request by fionera**
This is the same behaviour as $__timeInterval

### CODE REVIEW

**Comment by bossinc** [comment]
I am not sure why but this change is breaking a couple of tests.

**Comment by fionera** [comment]
This isn't breaking the tests. They are broken for some time now. I tested it locally and apparently the test is racy. I will open a PR to fix them

**Comment by fionera** [comment]
The tests will be fixed when https://github.com/grafana/sqlds/pull/83 gets merged and sqlds updated

**Comment by fionera** [comment]
PR was merged. Tests will be fixed with https://github.com/grafana/clickhouse-datasource/pull/273

**Review by bossinc — APPROVED** [review]

**Pull request merged**
