### PR TITLE
fix incorrect syntax for ad-hoc regexp filter

### PR DESCRIPTION
**Pull request by mshustov**
Steps to reproduce:
1. Create a panel
2. Apply a key-value regexp filter
Expected result: Filter is applied
Actual result: a query fails due to incorrect syntax 
```
error querying the database: clickhouse [execute]:: 400 code: Code: 62. DB::Exception: Syntax error (additional filter): failed at position 7 ('~'): ~ 'https://open.spotify.com/track/44ymejne8Roi7uT4lhiwCR' . Unrecognized token: '~'. (SYNTAX_ERROR)
```

After fix:

### Changelog
Fix support for ad-hoc regexp filters.

### CODE REVIEW

**Comment by asimpson** [comment]
@mshustov could we add a test case for this too? It looks great!

**Comment by mshustov** [comment]
@asimpson added, PTAL

**Review by asimpson — APPROVED** [review]
Looks great! :trophy:

**Comment by asimpson** [comment]
@mshustov could you add `ILIKE` to `cspell.config.json`? That will get Drone passing and we can merge.

**Comment by mshustov** [comment]
@asimpson done. could you merge on green CI, please?

**Review by asimpson — APPROVED** [review]

**Pull request merged**
