### PR TITLE
allow port to be a string and parse it as int64 in Go #241

### PR DESCRIPTION
**Pull request by v-electrolux**
Allow port to be a string and parse it as int64 in Go

Considered all three solution from this [thread](https://stackoverflow.com/questions/21151765/cannot-unmarshal-string-into-go-value-of-type-int64) and chose the one with custom unmarshaler, because:
- solution with ",string" option work with "port": "443" but no works with "port": 443
- solution with json.Number seems to me much more complicated (in terms of how much line of codes i must change)

### CODE REVIEW

**Comment by sasklacz** [comment]
Looks good to me but I'd like somebody with more go and this plugin experience to take a look as well.

**Review by scottlepp — COMMENTED** [review]
Hmm.  I've never seen this issue.  Does this work?
```
port: !!int ${CLICKHOUSE_PORT}
```

If not I suppose we could do below.   ( and change the client side to send a string )
```
Port               int64  `json:"port,string,omitempty"`
```

EDIT: looks like an issue where the env variable isn't getting set

**Comment by v-electrolux** [comment]
@scottlepp 
No, explicit type conversion does not work
```
Failed to start grafana. error: Datasource provisioning error: yaml: cannot decode !!str `${CLICKHOUSE_PORT}` as a !!int
```

I have following lines in my datasource all.yml file
```yaml
  - name: ClickHouse_Replica_1
    type: grafana-clickhouse-datasource
    editable: true
    jsonData:
      port: !!int ${CLICKHOUSE_PORT}
      server: $CLICKHOUSE_HOST_01
      username: $CLICKHOUSE_USER
      tlsSkipVerify: true
    secureJsonData:
      password: $CLICKHOUSE_PASSWORD
```

And my doocker-compose for custom grafana image
```yaml
  grafana:
    image: grafana:9.2.6-custom.6
    environment:
      - GF_DATABASE_TYPE=postgres
      - GF_DATABASE_HOST=192.168.1.14:4009
      - GF_DATABASE_NAME=grafana
      - GF_DATABASE_USER=grafana
      - GF_DATABASE_PASSWORD=grafana
      - INFLUX_URL=http://192.168.1.14:8086
      - INFLUX_DB_NAME=test_db
      - INFLUX_ADMIN_USER=test
      - INFLUX_ADMIN_PASSWORD=test
      - CLICKHOUSE_PORT=9000
      - CLICKHOUSE_HOST_01=192.168.1.14
      - CLICKHOUSE_HOST_02=192.168.1.15
      - CLICKHOUSE_HOST_03=192.168.1.16
      - CLICKHOUSE_USER=gf_user
      - CLICKHOUSE_PASSWORD=gf_pass
    deploy:
      mode: replicated
      replicas: 1
```

**Comment by bossinc** [comment]
Hello thank you for your PR! We decided to go in a different direction with #241 
Here is the PR that resolved this problem https://github.com/grafana/clickhouse-datasource/pull/293

**Pull request closed without merging**
