### PR TITLE
Update clickhouse-go to v2.4.3

### PR DESCRIPTION
**Pull request by jkaflik**
Resolves https://github.com/grafana/clickhouse-datasource/issues/231
Resolves https://github.com/grafana/clickhouse-datasource/issues/215

### CODE REVIEW

**Comment by mshustov** [comment]
cc @scottlepp @bossinc

**Comment by cletter7** [comment]
@jkaflik please run `go mod tidy` to remove unnecessary entries from `go.sum`

**Comment by jkaflik** [comment]
@cletter7 yes. thanks.

**Review by cletter7 — CHANGES_REQUESTED** [review]
LGTM, but could you please update from `main` @jkaflik? Currently there are conflicts because of recent changes.

**Review by scottlepp — APPROVED** [review]

**Pull request merged**
