### PR TITLE
Fix converters for driver v2 + JSON support

### PR DESCRIPTION
**Pull request by gingerwizard**
This fixes the converters for version 2.x of the driver - now in use on main. v2 requires strict use of types. 

We also add support for complex types - Tuple, Map and Nested. These are serialized to a JSON string. This thus supports the JSON type (results for this are returned as a Tuple). This allows uses to view JSON logs in the logs panel and explore.

Finally, to test all of this i've added significant tests so we don't miss issues with driver upgrades and types in the future.

This includes some IT tests - these use a Clickhouse instance (specified via env variables CLICKHOUSE_HOST and CLICKHOUSE_PORT - currently not secure). If these aren't specified we use a docker container. The former is appropriate for CI since it uses Drone (which uses docker itself for the tests and we don't support docker in docker yet @scottlepp @bossinc).  Can add support for a secure remote clickhouse instance if needed -this would actually allow us to test secure connections which is currently skipped.

### CODE REVIEW

**Comment by gingerwizard** [comment]
Closes https://github.com/grafana/clickhouse-datasource/issues/141

**Comment by gingerwizard** [comment]
The IT tests should skip if the env variables are not set and docker isn't available @scottlepp @bossinc - i can't see the drone failures - can you please share here?

**Comment by bossinc** [comment]
@gingerwizard 
``` + mage -v lint
Running target: Lint
exec: golangci-lint run ./...
pkg/plugin/driver_test.go:130:11: Error return value of `conn.Exec` is not checked (errcheck)
	conn.Exec("DROP TABLE simple_table")
	         ^
pkg/converters/converters.go:232:2: `name` is unused (structcheck)
	name string
	^
pkg/converters/converters.go:233:2: `kind` is unused (structcheck)
	kind interface{}
	^
Error: running "golangci-lint run ./..." failed with exit code 1```

**Comment by gingerwizard** [comment]
@bossinc we now support following env.

CLICKHOUSE_USERNAME
CLICKHOUSE_PASSWORD
CLICKHOUSE_SSL - set to `true` to use SSL
CLICKHOUSE_USE_DOCKER - set to `false` to use an external instance for IT tests

**Pull request merged**
