### PR TITLE
These two regex won't match with the complex column type now.

### PR DESCRIPTION
**Pull request by haudoing**
#783

### CODE REVIEW

**Comment by SpencerTorres** [comment]
Thanks for the issue + PR!

I see `Nullabe(IP)` was also changed, is this covered by a test case? I see theres some other ones in there but not specifically for array nullable.

**Comment by SpencerTorres** [comment]
Just noticed there's IPv4 and IPv6, could you add one more test case for IPv6?

Other than that, the PR looks good. I'll run it locally to verify

**Comment by SpencerTorres** [comment]
```go
"Nullable(IP)":              regexp.MustCompile(`Nullable\(IP`),
"Nullable(String)":          regexp.MustCompile(`Nullable\(String`),
```

It's very interesting that of all of the types there, these are the only two without the `^` prefix. I was worried this was intentional, but after seeing the original commits for [`String`](https://github.com/grafana/clickhouse-datasource/blob/0edd06bcbb2f57dbaf02dac9f3f70e04ab8334fa/pkg/converters/converters.go#L26) and [`IP`](https://github.com/grafana/clickhouse-datasource/blob/615978e7dce78e16a5a25da422be484950c1e1c4/pkg/converters/converters.go#L30), it seems this was just a small oversight.

I've run the tests and everything looks good. Thanks for the contribution 👍

**Comment by bossinc** [comment]
Thank you @haudoing and @SpencerTorres !

**Review by bossinc — APPROVED** [review]

**Pull request merged**
