### PR TITLE
Fix: Update Duration value in example traces dashboard

### PR DESCRIPTION
**Pull request by aangelisc**
Similar to #966 the duration displayed will now be the maximum value. I'm also explicitly using the `divide` function for readability.

### CODE REVIEW

**Review by alyssabull — DISMISSED** [review]

**Review by alyssabull — APPROVED** [review]

**Review by alyssabull — APPROVED** [review]

**Comment by SpencerTorres** [comment]
Just a note, division may not be the best operator here:

Issue: https://github.com/grafana/clickhouse-datasource/issues/720
Related code: https://github.com/ClickHouse/clickhouse-grafana-datasource/blob/280af29668f9977e9d4e779c033c4a297589905c/src/data/sqlGenerator.ts#L561-L575

**Comment by aangelisc** [comment]
> Just a note, division may not be the best operator here:
> 
> Issue: #720 Related code: https://github.com/ClickHouse/clickhouse-grafana-datasource/blob/280af29668f9977e9d4e779c033c4a297589905c/src/data/sqlGenerator.ts#L561-L575

That's interesting @SpencerTorres, thank you for picking up on that. Would you suggest truncating the data to millisecond precision instead?

**Comment by SpencerTorres** [comment]
I suppose it depends on how it's displayed, I want to avoid rounding to 0 and having that affect filtering

**Comment by aangelisc** [comment]
I see, my understanding of the ClickHouse [documentation](https://clickhouse.com/docs/en/sql-reference/functions/arithmetic-functions#divide) is that `divide` should always yield a float value (and I've tested this on ClickHouse play with an integer value for the duration). I believe this should be fine but we can switch to `multiply` instead if you'd prefer to be cautious. Let me know what you think!

image

**Comment by SpencerTorres** [comment]
I see the problem, I was previously using ` intDivOrZero`, which is much different...

Either one works then, should be fine as long as it preserves the float value 👍 

Thanks!

**Pull request merged**
