### PR TITLE
Support forward http headers option

### PR DESCRIPTION
**Pull request by shachakz**
Allows forwarding Grafana HTTP headers (such as x-grafana-org-id, x-grafana-user, ...) 
(Discussed in https://github.com/grafana/clickhouse-datasource/discussions/667#discussion-6128867)

* Added Forward HTTP Headers toggle to the plugin advanced settings section
* Expose "ForwardHeader" config in Settings method if configured to forward headers
* Set EnableMultipleConnections if forwarding http headers enabled
* Extract message headers during connect based on sqlds headers unique key
* Added some sqlds-plugin e2e test

UI Example:
image

### CODE REVIEW

**Comment by shachakz** [comment]
Hi, @asimpson 

Do you think we'll be able to review this anytime soon? 
Right now we use it as an unsigned plugin, published from the fork, but i'll be glad to use the official version 😄

**Comment by asimpson** [comment]
@shachakz yep, sorry for the back and forth. To fix the spelling linter could you incorporate these changes?

```diff
diff --git a/cspell.config.json b/cspell.config.json
index 81d20c4..02af0ca 100644
--- a/cspell.config.json
+++ b/cspell.config.json
@@ -70,6 +70,9 @@
     "Ulimits",
     "uuidv",
     "vectorator",
-    "WorkDir"
+    "WorkDir",
+    "elazarl",
+    "goproxy",
+    "Nonproxy"
   ]
 }
```

**Comment by shachakz** [comment]
> @shachakz yep, sorry for the back and forth. To fix the spelling linter could you incorporate these changes?
> 
> ```diff
> diff --git a/cspell.config.json b/cspell.config.json
> index 81d20c4..02af0ca 100644
> --- a/cspell.config.json
> +++ b/cspell.config.json
> @@ -70,6 +70,9 @@
>      "Ulimits",
>      "uuidv",
>      "vectorator",
> -    "WorkDir"
> +    "WorkDir",
> +    "elazarl",
> +    "goproxy",
> +    "Nonproxy"
>    ]
>  }
> ```

Done 👍

**Review by asimpson — APPROVED** [review]
Thanks for the hard work on this!

**Pull request merged**
